### ISSUE TITLE
Does not support password protected rar file

### ISSUE THREAD

**Issue by skchowdhury** [syedecryptr/unrar_file#2]
Hello
this is a good lib,i am using since 5 years in Android but now i want to use it for Flutter but it don't support password protected rar file.
can you help with that or do you have any plan for that
thank you

**Comment by syedecryptr** [comment]
Hi, since junrar supports password protected archives, I can look for adding that feature in this library this weekend. However that will not work for RAR5 since that is not supported by junrar, I have added a custom code for RAR5 in this library will have to see how to add the password protection RAR5. 
So if your requirement does not include RAR5 it is much doable.

**Comment by skchowdhury** [comment]
> Hi, since junrar supports password protected archives, I can look for adding that feature in this library this weekend. However that will not work for RAR5 since that is not supported by junrar, I have added a custom code for RAR5 in this library will have to see how to add the password protection RAR5.
> So if your requirement does not include RAR5 it is much doable.

Thank you so much sir.It will be very helpful for me if you add password protection support for this library i don't need RAR5 support now.
And thank you again for this great library.

**Comment by syedecryptr** [comment]
The feature is added in the version : [unrar_file: ^0.1.1](https://pub.dev/packages/unrar_file)

**Comment by skchowdhury** [comment]
Thank you so much sir
the password protected rar file is working fine.
thank you thousands times

**Comment by syedecryptr** [comment]
Can you close the other [issue](https://github.com/syedecryptr/unrar_file/issues/3) as well if it's working fine since that is also password protected RAR?

**Comment by skchowdhury** [comment]
@syedecryptr  sir did u check with the file i have uploaded ??
