### ISSUE TITLE
uncompress size is same compressed rar file

### ISSUE THREAD

**Issue by skchowdhury** [syedecryptr/unrar_file#3]
Hello
i have been using this library since five years in Java that is Junrar,i am using this also for Flutter but it's not working.
I have a file which size was 90 mb before compress and after it was 18 mb.
After uncompress with this library in Flutter it's size should be 90 mb but it is same as compressed size that was 18 mb and the file does not open also,
here is my code

`Directory applicationDirectory = await getExternalStorageDirectory();
  Directory desd = new Directory(
      applicationDirectory.path + "/");

  String dbPathEnglish = path.join(
      applicationDirectory.path, "Animation.rar");
  try {
    await UnrarFile.extract_rar(dbPathEnglish,  desd.path);
    desd.list(recursive: true, followLinks: false)
        .listen((FileSystemEntity entity) {
      print(entity.path);
    });
    print("extraction done.");
  } catch(e) {
    print("extraction failed");
  }`

please anyone tell me what's wrong here and give me a solution

**Comment by syedecryptr** [comment]
can you share the RAR file or link to that? Since it is working fine as demonstrated in the example folder, for that particular file I have to check.
Or you can analyze the same using the example folder, put that file in the assets directory, and change accordingly the path in the example(main.dart) and then try to run the example application. Share the log generated by the application.

**Comment by syedecryptr** [comment]
Or you can analyze the same using the example folder, put that file in the assets directory, and change accordingly the path in the example(main.dart) and then try to run the example application.

**Comment by skchowdhury** [comment]
Thank you sir
i am uploading file to drive and will share with you

**Comment by skchowdhury** [comment]
hi
here is the google drive link of file.its a sqlite database file,extention is .nomedia
https://drive.google.com/file/d/1FU4SwqntS48720CQmTuSiPoGGNfcdVMq/view?usp=sharing
rar password is : 123456
please please please please sir try it
thank you in advance

**Comment by syedecryptr** [comment]
Hi, 

`unrar l Animation.rar ` gives the output as :

![Screenshot from 2021-02-27 13-53-38](https://user-images.githubusercontent.com/9217595/109382017-c44a5280-7903-11eb-8694-2ec838647ec2.png)


clearly, the file you are trying to uncompress is password protected RAR5 which is not supported at the moment as described [here](https://github.com/syedecryptr/unrar_file/issues/2#issuecomment-785261624).

**Comment by skchowdhury** [comment]
Thank you so much sir
it's working fine
i really appreciate your effort.I want to donate you,how can i do that? if you don't mind
My country don't have paypal support 
so in that case how to pay ??

**Comment by syedecryptr** [comment]
Thank you for that.
You can buy me a coffee if my code helped you.
Here is the [link](https://pages.razorpay.com/pl_GgXZdPVoI8znVt/view ) where you can support me :)

**Comment by skchowdhury** [comment]
Thank you so much
i will try to donate with card.
Thank you again
