### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by moheb2000** [syedecryptr/unrar_file#5]
Hello! Thanks for this fantastic package.
I want to mention a quick thing about project license. Unrar can't have a free license like Apache or MIT because of "free utility for RAR archives" license:

> All copyrights to RAR and the utility UnRAR are exclusively owned by the author - Alexander Roshal.

Even junrar (unrar_file package is based on that) license is based on unrar utility license. see ![junrar license](https://github.com/junrar/junrar/blob/master/LICENSE).
I know maybe this isn't really an issue but I liked to mention that.
Thank a lot.

**Comment by syedecryptr** [comment]
yes, it seems you are right. I am no expert at licensing, but what you are implying makes sense. I will make an update about the license soon. Thanks for mentioning it.
