### ISSUE TITLE
using without files

### ISSUE THREAD

**Issue by Mike-3** [syedecryptr/unrar_file#6]
Is it possible to implement an interface without files (only data). I only have byte arrays available.

**Comment by syedecryptr** [comment]
you'll need to get the local RAR file path by saving the byte arrays(data) on the user's device. You cannot pass a byte array directly to the plugin yet.

Sample code if you need to store it 

`void save_rar(rar_file_buffer) async{
  Directory appDocDir = await getApplicationDocumentsDirectory();
  String appDocPath = appDocDir.path;
  var file_folder_path = join(appDocPath, "cache_rar_files");
  await new Directory(file_folder_path).create(recursive: true)
      .then((Directory directory) {
    rar_file_path = directory.path;
    //create new file.
    var file = new File(join(rar_file_path, "sample_file.rar"));
    file.writeAsBytesSync(epub_file_buffer);
  });
}`

**Comment by syedecryptr** [comment]
you'll need to get the local RAR file path by saving the byte arrays(data) on the user's device. You cannot pass a byte array directly to the plugin yet.

Sample code if you need to store it 
```
void save_rar(rar_file_buffer) async{
  Directory appDocDir = await getApplicationDocumentsDirectory();
  String appDocPath = appDocDir.path;
  var file_folder_path = join(appDocPath, "cache_rar_files");
  await new Directory(file_folder_path).create(recursive: true)
      .then((Directory directory) {
    rar_file_path = directory.path;
    //create new file.
    var file = new File(join(rar_file_path, "sample_file.rar"));
    file.writeAsBytesSync(epub_file_buffer);
  });
}
```

**Comment by Mike-3** [comment]
thanks
